### ISSUE TITLE
Use request uri template for low cardinality on span name.

### ISSUE THREAD

**Issue by jcchavezs** [luca-giardina/lara-zipkin#1]
Currently, the span naming is leading to high cardinality by using the requestURI. Instead you should try to use something with low cardinality and predictable if possible. E.g. instead of using `/things/123456` you might want to use `/things/{thing_id}`.

https://github.com/luca-giardina/lara-zipkin/blob/master/src/Middleware/LaraZipkinMiddleware.php#L25

**Comment by luca-giardina** [comment]
Could you be more specific please? What you think it could be a good improvement into the code for the main span instead of using the requested URI? a random code?
Remember that should be just the main span, inside you could use child spans
I'm going to improve the readme file :)

**Comment by jcchavezs** [comment]
By making span name high cardinality (i.e. unlimited number of possible names) what happens is that it becomes hard (near to impossible) to index those spans. Talking specifically about zipkin, when opening the UI you will see that there is a list of span names and that list will be endless with high cardinality.

![image](https://user-images.githubusercontent.com/3075074/53734719-12e3c400-3e85-11e9-8d46-27480ee3459f.png)


Usual practice is that you use something which is meaningful and predictable (e.g. route with wildcards as `/users/{user_id}` because all request matching that route will match there.

**Comment by lfaoro** [comment]
@luca-giardina what's the ETD for this issue please?

**Comment by luca-giardina** [comment]
with Laravel is very easy to do: Route::current()->uri()
I will do some changes switching to a route middleware because it's impossible to use a general middleware and have the laravel router ready.
Lumen needs to be tested with later versions because with 5.2.9 I can't get what I need. I will do it asap.

**Comment by jcchavezs** [comment]
Make sure this does not affect performance. If you have the opportunity of
trying this with real traffic would be very good.

We had to do some tricks in symfony and cache the route list because of
performance.

Den fre. 8. mar. 2019, 00:17 skrev luca-giardina <notifications@github.com>:

**Comment by jcchavezs** [comment]
Great, just a suggestion: if no pattern matched for route usually you mark
it with `not_found` or the http verb worst case.

Den lør. 9. mar. 2019, 20:13 skrev luca-giardina <notifications@github.com>:
